<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>08b740b6-5c78-401b-9b2c-e4837e3eaa02</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\db\Database.Lib\Database.Lib.csproj" />
    <ProjectReference Include="..\..\db\Database.Models\Database.Models.csproj" />
    <ProjectReference Include="..\..\db\database\database.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.8" />
  </ItemGroup>

</Project>
